### ISSUE TITLE
Support Kubernetes 1.11

### ISSUE THREAD

**Issue by mwilbz** [aws/aws-efs-csi-driver#10]
Right now it seems that only Kubernetes 1.13+ is supported by this driver, but my team is using Amazon's EKS, [which only supports up to Kubernetes 1.11](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html). Is it possible for this driver to support 1.11? I tried on our cluster just to see if I could resolve the issue, and get this error in the test pod's events:

```
Events:
  Type     Reason                  Age                        From                                               Message
  ----     ------                  ----                       ----                                               -------
  Warning  UnsupportedMountOption  114s (x131281 over 3h41m)  kubelet, <some-ip>  MountVolume.MountOptionSupport check failed for volume "efs-pv" : Mount options are not supported for this volume type
```

I did some digging and it looks like Kubernetes 1.11 [may not support mount options in CSI drivers](https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/volume/csi/csi_plugin.go#L299). I'm wondering if there are any workarounds, or if there was a way I could make the driver use TLS by default in a fork. Encryption in transit is a hard requirement for my team, so any solution would help us a lot!

Thanks in advance!

**Comment by leakingtapan** [comment]
@mwilbz the driver generally works on any k8s version that CSI 0.3 is supported. Since CSI spec itself involves really quick and mount option is the one feature that is missing in CSI 0.3 and is added recently in CSI 1.0 which requires k8s v1.13. 

Given that, I would recommend wait for [EKS support for k8s v1.13](https://github.com/aws/containers-roadmap/issues/30), if you don't want to maintain your own fork.

**Comment by mwilbz** [comment]
@leakingtapan thank you for the quick and detailed response!

Our use case: We are creating a brand new EKS cluster and wanted a way to mount EFS volumes to pods automatically. If support for 1.12 or 1.13 existed for EKS we likely would have tried to use this driver, but in the meantime we've found a workaround by mounting EFS onto our nodes and using Kubernetes' `local` volume type.

Thanks again for your help, I'll close the ticket since it seems difficult to support older versions of CSI with the same plugin, and in the meantime there is a workaround (for us, at least).

**Comment by mwilbz** [comment]
@leakingtapan I noticed you've added support for Kubernetes 1.11! Thanks for acting on the feedback :)
