### ISSUE TITLE
Transfer ownership to kubernetes-sigs as sig-aws subproject

### ISSUE THREAD

**Issue by leakingtapan** [aws/aws-efs-csi-driver#16]
The intent of this pull request is to complete the steps necessary to migrate aws/aws-efs-csi-driver repository to k8s-sig-aws as a subproject `github.com/kubernetes-sigs/aws-efs-csi-driver`.

The steps below use rules for [new](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-new-repositories) and [donated](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories) repositories:

Complete check-list:
- [x] Must contain the topic for the sponsoring SIG - e.g. k8s-sig-api-machinery. (Added through the Manage topics link on the repo page.)
- [x] Must adopt the Kubernetes Code of Conduct
- [x] All code projects use the Apache License version 2.0. Documentation repositories must use the Creative Commons License version 4.0.
- [ ] Must adopt the CNCF CLA bot, merge bot and Kubernetes PR commands/bots.
- [x] All OWNERS of the project must also be active SIG members
- [x] SIG membership must vote using lazy consensus to create a new repository
- [ ] SIG must already have identified all of their existing subprojects and code, with valid OWNERS files, in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml)
- [x] All contributors must have signed the CNCF Individual CLA (https://github.com/cncf/cla/blob/master/individual-cla.pdf) or CNCF Corporate CLA (https://github.com/cncf/cla/blob/master/corporate-cla.pdf)
- [ ] Licenses of dependencies are acceptable; project owners can ping [@caniszczyk](https://github.com/caniszczyk) for review of third party deps

**Comment by d-nishi** [comment]
received lazy consensus from +8 folks in SIG-AWS meeting held on 02/08/2018

**Comment by leakingtapan** [comment]
PR for the code of conduct change: #17

**Comment by d-nishi** [comment]
@leakingtapan - please close this issue as the subproject is going to Kubernetes SIG AWS and has nothing to do with AWS.

Also, this repository does not allow anyone other than AWS employees to contribute so I am not allowed to be assigned to any issue.
